trigger:
  batch: true
  branches:
    include:
    - main
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  containerRegistry: dockerhub-sanderobdeijn
  imageName: azuredevops.buildagent

jobs:
  - job:
    displayName: Build the Azure DevOps agent
    steps:
      - task: Docker@2
        displayName: Build
        inputs:
          containerRegistry: $(containerRegistry)
          buildContext: build-agents
          Dockerfile: 'build-agents/Dockerfile'
          repository: $(imageName)
          command: build
          tags: |
            $(Build.BuildId)
            latest