trigger:
  batch: true
  branches:
    include:
    - main
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  containerRegistry: dockerhub-sanderobdeijn
  imageName: azuredevops.buildagent

jobs:
  - job:
    displayName: Build the Azure DevOps agent
    steps:
      - task: Docker@2
        displayName: Build
        inputs:
          containerRegistry: $(containerRegistry)
          Dockerfile: 'Dockerfile'
          repository: $(imageName)
          command: build
          tags: |
            $(Build.BuildId)
            latest
      - task: Docker@2
        displayName: 'Push the Docker image to Dockerhub'
        inputs:
          containerRegistry: $(containerRegistry)
          repository: $(imageName)
          command: 'push'
          imageName: '$(ImageName)'
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) 
